name: Daily Economic Update

on:
  schedule:
    - cron: '0 15 * * *' # Runs every day at 3:00 PM UTC
  workflow_dispatch: # Allows you to run it manually with one click

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: Allows the robot to push the CSVs back to GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pipeline
        env:
          BLS_KEY: ${{ secrets.BLS_KEY }}
        run: python run_pipeline.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/processed/*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Latest BLS Data" && git push)